[34m[1mwandb[0m: [33mWARNING[0m No relevant files were detected in the specified directory. No code will be logged to your run.
  0%|                                                                                                                                                             | 0/100 [00:00<?, ?it/s]

EPOCH: 1


  0%|                                                                                                                                                             | 0/812 [00:10<?, ?it/s]
  0%|                                                                                                                                                             | 0/100 [00:10<?, ?it/s]
/data/rsulzer/miniconda3/envs/ppp/lib/python3.11/site-packages/torch/nn/functional.py:5962: UserWarning: Support for mismatched key_padding_mask and attn_mask is deprecated. Use same type for both instead.
  warnings.warn(
Error executing job with overrides: []
Traceback (most recent call last):
  File "/run/netsop/u/home-sam/home/rsulzer/remote_python/pixelspointspolygons/scripts/train.py", line 113, in main
    tt.train()
  File "/run/netsop/u/home-sam/home/rsulzer/remote_python/pixelspointspolygons/scripts/train.py", line 92, in train
    train_eval(
  File "/run/netsop/u/home-sam/home/rsulzer/remote_python/pixelspointspolygons/pixelspointspolygons/engine.py", line 182, in train_eval
    train_loss_dict, iter_idx = train_one_epoch(
                                ^^^^^^^^^^^^^^^^
  File "/run/netsop/u/home-sam/home/rsulzer/remote_python/pixelspointspolygons/pixelspointspolygons/engine.py", line 110, in train_one_epoch
    preds, perm_mat = model(x_image, x_lidar, y_input)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/rsulzer/miniconda3/envs/ppp/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/rsulzer/miniconda3/envs/ppp/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/netsop/u/home-sam/home/rsulzer/remote_python/pixelspointspolygons/pixelspointspolygons/models/pix2poly.py", line 253, in forward
    perm_mat2 = self.scorenet2(feats)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/data/rsulzer/miniconda3/envs/ppp/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/rsulzer/miniconda3/envs/ppp/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/netsop/u/home-sam/home/rsulzer/remote_python/pixelspointspolygons/pixelspointspolygons/models/pix2poly.py", line 78, in forward
    x = self.bn2(x)
        ^^^^^^^^^^^
  File "/data/rsulzer/miniconda3/envs/ppp/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/rsulzer/miniconda3/envs/ppp/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/rsulzer/miniconda3/envs/ppp/lib/python3.11/site-packages/torch/nn/modules/batchnorm.py", line 798, in forward
    return F.batch_norm(
           ^^^^^^^^^^^^^
  File "/data/rsulzer/miniconda3/envs/ppp/lib/python3.11/site-packages/torch/nn/functional.py", line 2822, in batch_norm
    return torch.batch_norm(
           ^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.12 GiB. GPU 0 has a total capacity of 47.50 GiB of which 311.25 MiB is free. Including non-PyTorch memory, this process has 46.87 GiB memory in use. Of the allocated memory 46.33 GiB is allocated by PyTorch, and 233.91 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
